version: '3'
services:
  job:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: Flask
    environment:
      - "PYTHONUNBUFFERED=1"
    ports:
      - 5000:5000
    command: python /app/init.py
